# Theoretical Questions:

### Question-1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy is a fundamental library in Python that provides support for large multi-dimensional arrays and matrices along with a collection of mathematical functions to operate on these arrays. It's also most valuable in scientific computing and data analysis because of its also efficiency and flexibility in handling numerical operations.

#### Purpose of NumPy:
there is some purposes of using Numpy

##### 1. Efficient Data Storage: 
NumPy arrays are more memory efficient than Python lists this feature making them ideal for large datasets.

##### 2.Matrix Operations: 
NumPy provides an large set of matrix operations including matrix multiplication, eigenvalue decomposition, and singular value decomposition making it an ideal choice for linear algebra operations.

##### 3.Numerical Computations: 
It provides highly optimized functions for mathematical operations such as linear algebra, Fourier transforms, and random number generation.

##### 4.Integration with Other Libraries:
NumPy integrates with other popular scientific computing and data analysis libraries in Python such as SciPy, Pandas, and Matplotlib.

##### 5.Data Analysis:
NumPy allows for manipulation of large datasets, which is important in data analysis where performance and memory efficiency are critical.

#### Advantages of NumPy in Scientific Computing:

##### 1.Performance: 
NumPy is created by using the fastest language C. thats why it making operations on arrays much faster than standard Python lists or loops.

##### 2.Memory Efficiency: 
NumPy arrays are more compact and efficient in memory usage compared to Python lists specially for large datasets.

##### 3.Broadcasting: 
NumPy can automatically handle arthmetic operations on arrays of different shapes and sizes without requiring manual reshaping and simplifying complex operations.

##### 4.Mathematical Functions:

##### 5.Indexing and Slicing: 
NumPy offers powerful indexing, slicing, and reshaping features that make it easier to manipulate and transform data compared to lists.

#### How it Enhancing Python's Capabilities for Numerical Operations

##### 1.Speed: 
NumPy vectorized operations and optimized algorithms make numerical computations significantly faster than using Python's built-in data structures and functions.

##### 2.Convenience: 
NumPy provides a concise and expressive syntax for performing complex numerical operations making it easier to write and read numerical code.

##### 3.Flexibility: 
NumPy support for multi-dimensional arrays and matrices enables you to perform a wide range of numerical operations, from simple arithmetic to complex linear algebra and statistical analysis.

## Question- 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#### Comparison of np.mean() and np.average() in NumPy :-

Both np.mean() and np.average() are used to calculate the average of a dataset in NumPy.

##### Similarities:
Both functions calculate the average of a dataset.And can handle multi-dimensional arrays.

#### Differences:
##### Weights: 
np.average() allows for weight average wherea np.mean() does not. In np.average() you can also specify weights for each element in the dataset using the weights parameter.
##### Axis: 
np.mean() can operate along a specific axis of a multi-dimensional array whereas np.average() does not have this capability.

#### When to use each:
##### Use of np.mean():
You want to calculate the simple arithmetic mean of a dataset.
You need to operate along a specific axis of a multi-dimensional array.
##### Use of np.average():
You need to calculate a weighted average of a dataset.
You want to specify weights for each element in the dataset.

In [1]:
import numpy as np

In [2]:
#Example
import numpy as np

data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)
print(mean_value) 

weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
weighted_average = np.average(data, weights=weights)
print(weighted_average)
#weighted_average_1 = np.mean(data, weights=weights)
#print(weighted_average_1)
#it will through an error

3.0
3.2


## Question-3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy Array Along Different Axes
NumPy provides some methods to reverse an array along different axes.
#### 1. np.flip():
np.flip() is a function that reverses the elements of an array along a specified axis. It returns a view of the original array not a copy.

In [3]:
#Example of 1D array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
print(arr)
print(reversed_arr)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
# Example of 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
reversed_arr1 = np.flip(arr1, axis=0)
reversed_arr1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [6]:
reversed_arr1 = np.flip(arr1, axis=1)
reversed_arr1

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

#### 2. arr[::-1]:-

This method uses slicing to reverse the array. It also returns a view of the original array, not a copy.

In [7]:
#Example of 1D array
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)

[1 2 3 4 5]


In [8]:
reversed_arr_1 = arr_1[::-1]
print(reversed_arr_1)

[5 4 3 2 1]


In [9]:
#Example of 2D array
arr_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
reversed_arr_2 = arr_2[::-1, :]
reversed_arr_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [11]:
reversed_arr_2d = arr_2[:, ::-1]
reversed_arr_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Both methods achieve the same result, but np.flip() is more explicit and flexible.

## Question-4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In NumPy we can determine the data type of elements in an array using the ' .dtype() ' attribute. This attribute returns a dtype object which describes the type of elements in the array.

In [12]:
#Example
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.dtype


dtype('int32')

In [14]:
arr2 = np.array(["Lokanath", "Ajay", "Pwskills"])
arr2
arr2.dtype

dtype('<U8')

### Importance of Data Types in Memory Management and Performance:
Data types play a crucial role in memory management and performance in NumPy arrays.

#### Memory Management:
##### Memory allocation: 
The data type of an array determines the amount of memory allocated for each element. 
##### Memory efficiency: 
Using the correct data type can help reduce memory usage, which is essential for large datasets.

#### Performance:
##### efficiency: 
Operations on arrays with smaller data types are generally faster than those with larger data types. Data types can affect performance.
##### Vector operation: 
NumPy vector operations are optimized for specific data types. Using the correct data type can enable vectorization.

## Question-5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy ndarray stands for n- dimensional array. it is a multi-dimensional array of fixed-size, homogeneous elements. It is the core data structure in NumPy and it also providing an efficient and flexible way to store and manipulate large datasets.

### Key Features of ndarrays:
#### Multi-dimensional: 
ndarrays can have any number of dimensions from 1D to nD.
#### Homogeneous: 
All elements in an ndarray have the same data type which is specified by the dtype attribute.
#### Fixed-size: 
The size of an ndarray is fixed at creation time and cannot be changed later.
#### Contiguous memory allocation: 
ndarrays store their elements in contiguous blocks of memory which enables efficient access and manipulation.
#### Vectorized operations: 
It also support vectorized operations which allow we to perform operations on entire arrays at one time.

#### Differences from Standard Python Lists:

##### 1.Homogeneous: 
Python lists can contain elements of different data types where ndarrays require all elements to have the same data type.
##### 2.Memory allocation: 
Python lists store their elements as separate objects which can used large size of memory and slower access times. ndarrays on the other hand store their elements in contiguous memory blocks.
##### 3.Performance: 
ndarrays are generally faster and more efficient than Python lists specially for numerical computations and large datasets.
##### 4.Vectorized operations: 
ndarrays support vectorized operations which are not available in Python lists.
##### 5.Indexing and slicing: 
ndarrays support advanced indexing and slicing capabilities including multi-dimensional indexing and broadcasting.
##### 6.Data type specification: 
ndarrays require explicit data type specification where Python lists do not.
##### 7.Memory usage: 
ndarrays can be more memory-efficient than Python lists specially for large datasets since they store elements in contiguous block of memory.

In [15]:
#Example of a python list
python_list = [1, 2, 3, 4, 5]
python_list

[1, 2, 3, 4, 5]

In [16]:
# Create an ndarray
ndarray = np.array([1, 2, 3, 4, 5])
ndarray


array([1, 2, 3, 4, 5])

In [17]:
result = ndarray * 2
result 

array([ 2,  4,  6,  8, 10])

## Question-6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#### 1.Memory Efficiency:
NumPy arrays store elements in a contiguous block of memory which helps to access it more faster than python list. In the case of  Python lists it store elements as separate objects resulting in memory fragmentation and slower access times.
#### 2.Vectorized Operations:
NumPy arrays support vectorized operations which allow we to perform operations on entire arrays at one time rather than iterating over individual elements. This leads to significant performance gains, especially for large datasets. Python lists, on the other hand, require explicit iteration over elements, which can be slow.
#### 3.Data Type Specialization:
NumPy arrays are specialized for specific data types, such as integers, floats, or complex numbers. This specialization allows NumPy to optimize memory allocation and access patterns for each data type, leading to improved performance.
#### 5.Low-Level Optimizations:
NumPy arrays are implemented in C, which allows for low-level optimizations and direct access to hardware resources. This results in faster execution times for numerical operations.

In [18]:
# Example of a large Python list
import time
python_list = [i for i in range(1000000)]
start = time.time()
result_list = [x * 2 for x in python_list]
end = time.time()
print("Executation time:",{end - start})


Executation time: {0.14078712463378906}


In [19]:
# Example of a large NumPy array
numpy_array = np.arange(1000000)
start = time.time()
result_array = numpy_array * 2
end = time.time()
print("Executation time:",{end - start})

Executation time: {0.007998228073120117}


## Question-7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy vstack() and hstack() are two functions used to stack arrays vertically and horizontally respectively. Both functions are used to combine multiple arrays into a single array but they differ in the way they stack the arrays.

#### vstack() Function:
The vstack() function stacks arrays vertically meaning it combines arrays by adding rows.

In [20]:
#Example of vstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.vstack((arr1, arr2))

In [21]:
arr1

array([1, 2, 3])

In [22]:
arr2

array([4, 5, 6])

In [23]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

#### hstack() Function:
The hstack() function stacks arrays horizontally meaning it combines arrays by adding columns.

In [24]:
#Example of hstack()
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])
arr6 = np.hstack((arr4, arr5))

In [25]:
arr4

array([1, 2, 3])

In [26]:
arr5

array([4, 5, 6])

In [27]:
arr6

array([1, 2, 3, 4, 5, 6])

## Question-8.  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy fliplr() and flipud() are two methods used to flip arrays horizontally and vertically respectively. Both methods are used to reverse the order of elements in an array but they differ in the direction of flipping.

#### fliplr() Method:
The fliplr() method flips an array horizontally means it reverses the order of elements along the horizontal axis . This method is useful for flipping 2D arrays such as matrices.

In [28]:
#Example of fliplr
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# Flip the array horizontally using fliplr()
flipped_array = np.fliplr(arr1)
print(flipped_array)

[[3 2 1]
 [6 5 4]]


#### flipud() Method:
The flipud() method flips an array vertically means it reverses the order of elements along the vertical axis . This method is  also useful for flipping 2D arrays such as images or matrices.

In [29]:
#Example of flipud()
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
flipped_array = np.flipud(arr1)
print(flipped_array)

[[4 5 6]
 [1 2 3]]


### Effects on Various Array Dimensions:
#### 1D Arrays: 
Both fliplr() and flipud() methods have no effect on 1D arrays as there is only one axis to flip.
#### 2D Arrays: 
fliplr() flips the array horizontally while flipud() flips the array vertically.
#### 3D Arrays: 
fliplr() flips the array horizontally along the second axis , while flipud() flips the array vertically along the first axis .
#### Higher-Dimensional Arrays: 
Both methods can be used to flip arrays along specific axes using the axis parameter.

## Question-9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into sub-arrays along a specified axis. It is a convenient way to divide an array into smaller parts which can be useful for various applications such as data processing, machine learning, and scientific computing.

### Basic Syntax:
The basic syntax is array_split() 

#### Even Splits:
When object in an array is an integer the array is split into equal-sized sub-arrays along the specified axis.

In [30]:
#Example of even split
arr = np.arange(12)
sub_arr = np.array_split(arr, 3)
print(sub_arr)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


#### Uneven Splits:
When object in an array is a list of integers the array is split at the specified object along the specified axis.

In [31]:
#Example of Uneven splits
arr1 = np.arange(12)
sub_arr1 = np.array_split(arr1, [3, 7])
print(sub_arr1)

[array([0, 1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]


#### Handling Uneven Splits:
When the array cannot be split evenly the array_split() method will adjust the size of the sub-arrays to accommodate the remaining elements.

In [32]:
# Example of handeling Uneven splits
arr = np.arange(10)
sub_arr = np.array_split(arr, 3)

print(sub_arr)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## Question-10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

NumPy is a powerful library for large numerical computation in Python. There are two key concepts that contribute to its efficiency are vectorization and broadcasting.

#### Vectorization:
Vectorization is the process of performing operations on entire arrays at once, rather than iterating over individual elements. This is achieved through the use of optimized C code and specialized CPU instructions.

In [33]:
#Example of Vectorization

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

arr3 = arr1 + arr2

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
arr2

array([ 6,  7,  8,  9, 10])

In [36]:
arr3

array([ 7,  9, 11, 13, 15])

#### Broadcasting:
Broadcasting is the process of aligning arrays with different shapes and sizes to perform operations on them. This is achieved by adding dimensions to the arrays and replicating values as needed.

In [37]:
# Example of Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])

arr3 = arr1 * arr2


In [38]:
arr1

array([1, 2, 3])

In [39]:
arr2

array([[4],
       [5],
       [6]])

In [40]:
arr3

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

### Contribution to Efficient Array Operations:
Vectorization and broadcasting contribute to efficient array operations in several ways:

#### Reduced Looping: 
By performing operations on entire arrays at once, vectorization reduces the need for explicit looping, which can be slow in Python.
#### Optimized C Code: 
NumPy optimized C code and specialized CPU instructions enable fast execution of vectorized operations.
#### Memory Efficiency: 
Broadcasting allows NumPy to perform operations on arrays with different shapes and sizes without creating intermediate arrays, reducing memory usage and allocation overhead.
#### Flexibility: 
Broadcasting enables NumPy to perform operations on arrays with different numbers of dimensions, making it a flexible and powerful tool for numerical computation.

# Practical Questions:

## Question-1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [41]:
import numpy as np

arr = np.random.randint(1, 101, (3, 3))

In [42]:
arr

array([[52, 27, 57],
       [22, 24, 24],
       [13, 52, 65]])

In [43]:
arr_invers = arr.T

In [44]:
arr_invers

array([[52, 22, 13],
       [27, 24, 52],
       [57, 24, 65]])

## Question-2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [45]:
import numpy as np
arr = np.random.randint(1, 101, 10)
arr1 = arr.reshape(2, 5)
arr2 = arr.reshape(5, 2)


In [46]:
arr

array([38, 90, 79, 87, 27, 70, 91, 25, 26, 95])

In [47]:
arr1

array([[38, 90, 79, 87, 27],
       [70, 91, 25, 26, 95]])

In [48]:
arr2

array([[38, 90],
       [79, 87],
       [27, 70],
       [91, 25],
       [26, 95]])

## Question-3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [49]:
arr = np.random.rand(4,4)

In [50]:
arr

array([[0.45934035, 0.61464695, 0.51005129, 0.64872571],
       [0.98916169, 0.50829968, 0.38636271, 0.60007565],
       [0.12974548, 0.47891221, 0.17446693, 0.20689714],
       [0.67325993, 0.8971641 , 0.55714184, 0.63438912]])

In [51]:
new_arr = np.pad(arr,1)

In [52]:
new_arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.45934035, 0.61464695, 0.51005129, 0.64872571,
        0.        ],
       [0.        , 0.98916169, 0.50829968, 0.38636271, 0.60007565,
        0.        ],
       [0.        , 0.12974548, 0.47891221, 0.17446693, 0.20689714,
        0.        ],
       [0.        , 0.67325993, 0.8971641 , 0.55714184, 0.63438912,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

## Question-4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [59]:
arr = np.arange(10,60,5)

In [60]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [61]:
arr.dtype

dtype('int32')

## Question-5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [63]:
arr = np.array(['python', 'numpy', 'pandas'])

In [64]:
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [65]:
upper_arr = np.char.upper(arr)

In [66]:
upper_arr

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [67]:
lower_arr = np.char.lower(arr)

In [68]:
lower_arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [71]:
title_arr = np.char.capitalize(arr)

In [72]:
title_arr

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

## Question-6.  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [76]:
arr = np.array(['pwskills', 'data' , 'science', 'generative' 'ai'])


In [77]:
arr

array(['pwskills', 'data', 'science', 'generativeai'], dtype='<U12')

In [93]:
# space_arr = np.array([' '.join(arr) for i in arr ])
spaced_arr = np.array([' '.join(i) for i in arr])

In [94]:
spaced_arr

array(['p w s k i l l s', 'd a t a', 's c i e n c e',
       'g e n e r a t i v e a i'], dtype='<U23')

## Question-7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [7]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr2 = np.array([[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])

In [4]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
arr1 + arr2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [9]:
arr1 * arr2

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [13]:
arr1 - arr2

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [10]:
arr2 - arr1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [12]:
arr1 / arr2

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

## Question- 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [17]:
arr = np.eye(5)

In [18]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
dig_item = np.diag(arr)

In [20]:
dig_item

array([1., 1., 1., 1., 1.])

## Question-9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [23]:
arr = np.random.randint(0,1000,100)

In [24]:
arr

array([568, 266, 956,  92, 536, 193, 885, 867, 706, 137, 638, 358,  32,
       850, 620, 350, 650, 886, 300, 503, 902, 697, 920, 761, 250, 368,
       567, 979, 607, 700, 843, 791, 601,  82, 292, 161, 776, 489, 267,
       215, 194, 224, 431, 708, 489, 471, 957, 327, 302, 977, 377, 361,
       536, 122,  98, 420, 445, 748, 333, 397, 361, 275, 243, 121,  61,
       707,   2, 813, 388, 302, 342, 965, 405, 336, 393, 619,  11, 996,
       970, 494, 746, 979, 622,  46,  93,  38, 747, 526, 567, 327, 510,
       674,  27, 903, 933, 207,  18,  22,  73, 251])

In [25]:
prime_numbers = []
for num in arr:
    if num <= 1:
        continue
    elif num == 2:
        prime_numbers.append(num)
    else:
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            prime_numbers.append(num)

In [26]:
prime_numbers

[193, 137, 503, 761, 607, 601, 431, 977, 397, 61, 2, 619, 11, 73, 251]

## Question-10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [27]:
temperatures = np.random.randint(20, 30, 30)

In [28]:
temperatures

array([23, 25, 27, 20, 21, 26, 29, 28, 28, 24, 22, 26, 20, 20, 22, 28, 29,
       27, 22, 24, 28, 28, 27, 28, 26, 26, 24, 24, 22, 25])

In [29]:
weekly_averages = []
for i in range(0, 30, 7): 
    weekly_average = np.mean(temperatures[i:i+7])
    weekly_averages.append(weekly_average)

In [31]:
weekly_averages

[24.428571428571427, 24.0, 25.714285714285715, 26.142857142857142, 23.5]